CREATE TABLE "dinner_plans" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "day" INTEGER,
    "recipie_id" INTEGER NOT NULL,
    "servings" INTEGER NOT NULL,
    "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY ("recipie_id") REFERENCES "recipies" ("id") ON DELETE CASCADE
);

CREATE TABLE "non_dinner_plans" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "meal_type" INTEGER NOT NULL,
    "recipie_id" INTEGER NOT NULL,
    "servings" INTEGER NOT NULL,
    "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY ("recipie_id") REFERENCES "recipies" ("id") ON DELETE CASCADE
);

CREATE TABLE "extra_items" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "name" TEXT NOT NULL,
    "quantity" REAL NOT NULL,
    "unit_id" INTEGER NOT NULL,
    "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY ("unit_id") REFERENCES "units" ("id") ON DELETE CASCADE
)
